version: '3.8'  # Spécifiez la version de Docker Compose

services:
  mysql:  # Nom du service
    image: mysql:8  # Image MySQL, ici version 8
    container_name: mysql  # Nom du conteneur
    environment:
      
      MYSQL_ROOT_PASSWORD: root_password  # Mot de passe root (à remplacer par un mot de passe sécurisé)
      MYSQL_DATABASE: tpachato  # Nom de la base de données
    ports:
      - "3306:3306"  # Redirection du port 3306
    volumes:
      - mysql_data:/var/lib/mysql  # Volume pour persister les données

  tpachatproject:
    image: khouloudzograni/tpachatproject:latest
    container_name: tpachatproject
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tpachato
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
    ports:
      - "8089:8089"  # Expose the Spring Boot service
    depends_on:
      - mysql  # Ensures MySQL starts before Spring Boot app


volumes:
  mysql_data:
